---
- hosts: linux
  tasks:
  - name: upload file to server
    copy:
      src: /root/program.sh
      dest: /home/ansible/program.sh
      mode: 0755
  - name: modify the scripti
    lineinfile:
      state: present
      dest: /home/ansible/program.sh
      regexp: 'HOST='
      line: HOST={{ ansible_hostname }}
  - name: run script
    shell: /home/ansible/program.sh
    register: output
  - debug: msg=" output is {{output.stdout}}"
