---
- hosts: linux
  become: yes
  tasks:
  - name: create fact directory
    file:
      path: /etc/ansible/facts.d
      recurse: yes
      state: directory
  - name: create the script using template
    template:
      src=/root/datetime.sh.j2
      dest=/etc/ansible/facts.d/date_time.fact
      mode=0755
  - name: print the custom facts
    debug:
      msg: "custom facts is {{ ansible_local.date_time }}"
