---
- hosts: linux
  vars:
    training:
      topic: ansible
      trainer: vijay
      lab: aws
  tasks:
  - name: print dictionary variables
    debug:
      msg: " key is {{ item.key }} and value is {{ item.value }} "
    with_dict: "{{ training }}"
