---
- hosts: linux
  vars:
    training:
      topic: ansible
      trainer: vijay
      lab: aws
  tasks:
  
  - name: print dictionary variables
    debug:
      msg: "{{ training['topic'] }}"

  - name: print dictionary variables
    debug:
      msg: "{{ training.topic }}" 
