---
- hosts: linux
  vars: 
    games:
      - cricket
      - football
      - nondi
      - baseball
      - basketball
      - volleyball
  tasks:
  - name: print list variables
    debug:
      msg: "{{ games [4]}}"
