---
- hosts: linux
  tasks:
  - name: create multiple directory in linux host
    file: 
      path: " {{ item }} "
      state: directory
    with_items: 
    - '/home/ansible/var1'
    - '/home/ansible/var2'
    - '/home/ansible/var3'
